### ISSUE TITLE
Little review

### ISSUE THREAD

**Issue by vguen** [PixiesRAC/Saroumane#3]
Why don't you use a namespace instead of a classs ? https://github.com/royal-alambic-club/RAC_RenifleurDuXul/blob/df2b01c9e727215f9014ab894c1ebf7c3b713ba6/include/time/TimeHandler.h#L10-L35

Why is this attribute `static` don't you only need the instance attribute to be static ? If the `ofstream` is not `static` you could use its default destructor to release its resources, thus you won't have to check if it still open when you delete the instance. Moreover is it necessary for the attribute to be `public` instead of `private` ? https://github.com/royal-alambic-club/RAC_RenifleurDuXul/blob/df2b01c9e727215f9014ab894c1ebf7c3b713ba6/include/log/LogHandler.h#L62

**Comment by PixiesRAC** [comment]
About the class instead of the namespace, Actually i don't know if i will modify this in the futur.
If i will, it will be less complex.

About the static ofstream, Where did you see that the destructor of ofstream close the open file ?.
more than that, if i don't use static, i need to put this attribut in public and the instance attribute in public too in order to use the ofstream. SO I think it's better to let this code.

What do you think about thach ?

In addition to that, you right about the constructor missing in private side i will add it.

**Comment by PixiesRAC** [comment]
https://github.com/royal-alambic-club/RAC_RenifleurDuXul/pull/4/files
